name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_display: classic
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 14    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: all
          plugin_isocalendar: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: rjdbcm                         # User
          token: ${{ secrets.METRICS_TOKEN }}
