name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_display: classic
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 14    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: all
          plugin_isocalendar: yes
          token: ${{ secrets.METRICS_TOKEN }}
